### ISSUE TITLE
VT API V3 Update on virustotal.py

### ISSUE THREAD

**Issue by devnull044** [crhenr/freki#11]
Enhancement I wouldn't mind helping with, but may want to update to using the V3 api. Not sure when VT plans on dropping V2 support.

-https://developers.virustotal.com/v3.0/reference

**Comment by cristianzsh** [comment]
Done [#987c94d](https://github.com/crhenr/freki/commit/987c94dc47887543297de50dfdc9a1cd209bec99)

Thanks for the suggestion.
