### ISSUE TITLE
Not exposing when using docker-compose

### ISSUE THREAD

**Issue by sam-morin** [crhenr/freki#15]
No matter what I try I cannot access freki web

git clone https://github.com/crhenr/freki.git
cd freki
nano .env (to edit keys)
docker-compose up

Here is my output:
freki        | Waiting for MySQL to be up...
freki        | Waiting for MySQL to be up...
freki_db     | 2023-01-09  2:33:00 0 [Note] /usr/bin/mysqld (server 10.6.11-MariaDB) starting as process 1 ...
freki_db     | 2023-01-09  2:33:00 0 [Note] InnoDB: Compressed tables use zlib 1.2.13
freki_db     | 2023-01-09  2:33:00 0 [Note] InnoDB: Number of pools: 1
freki_db     | 2023-01-09  2:33:00 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
freki_db     | 2023-01-09  2:33:00 0 [Note] mysqld: O_TMPFILE is not supported on /var/tmp (disabling future attempts)
freki_db     | 2023-01-09  2:33:00 0 [Note] InnoDB: Using Linux native AIO
freki_db     | 2023-01-09  2:33:00 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
freki_db     | 2023-01-09  2:33:00 0 [Note] InnoDB: Completed initialization of buffer pool
freki_db     | 2023-01-09  2:33:00 0 [Note] InnoDB: 128 rollback segments are active.
freki_db     | 2023-01-09  2:33:00 0 [Note] InnoDB: Creating shared tablespace for temporary tables
freki_db     | 2023-01-09  2:33:00 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
freki_db     | 2023-01-09  2:33:00 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
freki_db     | 2023-01-09  2:33:00 0 [Note] InnoDB: 10.6.11 started; log sequence number 42282; transaction id 14
freki_db     | 2023-01-09  2:33:00 0 [Note] Plugin 'FEEDBACK' is disabled.
freki_db     | 2023-01-09  2:33:00 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
freki_db     | 2023-01-09  2:33:00 0 [Note] InnoDB: Buffer pool(s) load completed at 230109  2:33:00
freki_db     | 2023-01-09  2:33:00 0 [Note] Server socket created on IP: '0.0.0.0'.
freki_db     | 2023-01-09  2:33:00 0 [Note] Server socket created on IP: '::'.
freki_db     | 2023-01-09  2:33:00 0 [Warning] 'user' entry '@2f13d7913c93' ignored in --skip-name-resolve mode.
freki_db     | 2023-01-09  2:33:00 0 [Warning] 'proxies_priv' entry '@% root@2f13d7913c93' ignored in --skip-name-resolve mode.
freki_db     | 2023-01-09  2:33:00 0 [Note] /usr/bin/mysqld: ready for connections.
freki_db     | Version: '10.6.11-MariaDB'  socket: '/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server
freki_db     | 2023-01-09  2:33:00 3 [Warning] Access denied for user 'root'@'192.168.99.99' (using password: NO)
freki        | Starting Freki...
freki        | [2023-01-09 02:33:03 +0000] [1] [INFO] Starting gunicorn 20.1.0
freki        | [2023-01-09 02:33:03 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
freki        | [2023-01-09 02:33:03 +0000] [1] [INFO] Using worker: sync
freki        | [2023-01-09 02:33:04 +0000] [25] [INFO] Booting worker with pid: 25
freki        | [2023-01-09 02:33:04 +0000] [26] [INFO] Booting worker with pid: 26
freki        | [2023-01-09 02:33:04 +0000] [27] [INFO] Booting worker with pid: 27
freki        | [2023-01-09 02:33:04 +0000] [28] [INFO] Booting worker with pid: 28
freki        | [2023-01-09 02:33:04 +0000] [29] [INFO] Booting worker with pid: 29

Navigating to my docker host's IP and port is unable to connect
I've tried editing passwords/keys, leaving them the same, etc. with absolutely no luck :(

Can someone tell me what I may be doing wrong?

I followed all the steps exactly in: https://cristian.sh/freki/admin/run-docker.html#install-docker-and-docker-compose

Thanks!

**Comment by Manish5513** [comment]
hey, were you able to fix the issue?

**Comment by cristianzsh** [comment]
Hello guys.

I find out that there was an error with the SQLAlchemy module. The commit [efe0363](https://github.com/cristianzsh/freki/commit/efe03631825a94e9c31b247122d4bd36bc9c6306) fix this issue.

You should now be able to access Freki at http://192.168.99.100

**Comment by cristianzsh** [comment]
Hello guys.

I found out that there was an error with the SQLAlchemy module. The commit [efe0363](https://github.com/cristianzsh/freki/commit/efe03631825a94e9c31b247122d4bd36bc9c6306) fix this issue.

You should now be able to access Freki at http://192.168.99.100

**Comment by sam-morin** [comment]
It's working now. Thank you!!
